name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.3.0
homepage: https://github.com/rinukkusu/spotify-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.1
  oauth2: ^1.5.0

dev_dependencies:
  test: ^1.5.1
  build_runner: ^1.1.1
  json_serializable: ^3.2.5
  pedantic: ^1.9.0
