name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.2.0
homepage: https://github.com/rinukkusu/spotify-dart
authors:
- rinukkusu <rinukkusu@auen.land>
- Chance Snow <git@chancesnow.me>
- Hayri Bakici
- Wesley Batista
- ebarnsli
- Ivan Mogilevsky <mogilevsky.ivan@gmail.com>
- Igor Katsuba <katsuba.igor@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0
  json_annotation: ^3.0.1
  oauth2: ^1.5.0

dev_dependencies:
  test: ^1.5.1
  build_runner: ^1.1.1
  json_serializable: ^3.2.5
