name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.15.0
homepage: https://github.com/rinukkusu/spotify-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.6.0
  json_annotation: ^4.9.0
  oauth2: ^2.0.5
  meta: ^1.17.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
