name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.13.7
homepage: https://github.com/rinukkusu/spotify-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.2.0
  json_annotation: ^4.8.1
  oauth2: ^2.0.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.1
