name: spotify
description: An incomplete dart library for interfacing with the Spotify Web API.
version: 0.9.1
homepage: https://github.com/rinukkusu/spotify-dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.8.0
  oauth2: ^2.0.0
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.16.5
  build_runner: ^2.0.3
  json_serializable: ">=4.1.1 <7.0.0"
